# Schema for the configuration files of the farm_asset module.
farm_asset.type.*:
  type: config_entity
  label: 'farm asset type'
  mapping:
    id:
      type: string
      label: 'Machine-readable name'
    label:
      type: label
      label: 'Type'
    description:
      type: text
      label: 'Description'
    workflow:
      type: string
      label: 'Workflow'
    new_revision:
      type: boolean
      label: 'Create new revision'

condition.plugin.farm_asset_type:
  type: condition.plugin
  mapping:
    bundles:
      type: sequence
      sequence:
        type: string
