site_name: farmOS 2.x Docs
nav:
  - Development:
    - API:
      - Introduction: development/api/index.md
      - Authentication: development/api/authentication.md
      - Changes: development/api/changes.md
    - Module:
      - Getting started: development/module/index.md
      - Fields: development/module/fields.md
      - OAuth: development/module/oauth.md
      - Roles: development/module/roles.md
    - Environment:
      - Getting started: development/environment/index.md
      - Docker: development/environment/docker.md
      - PostgreSQL: development/environment/postgresql.md
      - Drush: development/environment/drush.md
      - Composer: development/environment/composer.md
      - Debugging: development/environment/debug.md
      - Automated tests: development/environment/tests.md
      - Coding standards: development/environment/code.md
      - Documentation: development/environment/documentation.md
  - Hosting:
    - 1.x Migration: hosting/migration.md
theme:
  name: material
  palette:
    primary: green
    accent: orange
markdown_extensions:
  - toc:
      permalink: true
