site_name: farmOS 2.x
nav:
  - farmOS: index.md
  - API:
    - Introduction: api/index.md
    - Changes: api/changes.md
  - Development:
    - Getting started: development/index.md
    - Docker: development/docker.md
    - PostgreSQL: development/postgresql.md
    - Drush: development/drush.md
    - Composer: development/composer.md
    - Debugging: development/debug.md
    - Automated tests: development/tests.md
    - Coding standards: development/code.md
theme: readthedocs
