blank_issues_enabled: true
contact_links:
  - name: farmOS Community Forum
    url: https://farmOS.discourse.group/
    about: Questions, support requests, and feature discussions take place in the forum.

