content:
  equipment:
    type: entity_reference_autocomplete
    weight: 55
    region: content
    settings:
      match_operator: CONTAINS
      match_limit: 10
      size: 60
      placeholder: ''
    third_party_settings: {  }
